# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lab < Formula
  desc "Lab wraps Git or Hub, making it simple to clone, fork, and interact with repositories on GitLab"
  homepage "https://github.com/zaquestion/lab"
  version "0.20.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/zaquestion/lab/releases/download/v0.20.0/lab_0.20.0_darwin_amd64.tar.gz"
    sha256 "6580c00fbd26d0368d2e2ca77b556795cf355ccc3fdb9e2c15af012aa5f15a90"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/zaquestion/lab/releases/download/v0.20.0/lab_0.20.0_linux_amd64.tar.gz"
    sha256 "998340ffac7bd7f11638fa5b4bfd28e6e8bd896ba406d27d9028188a1985ac0f"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/zaquestion/lab/releases/download/v0.20.0/lab_0.20.0_linux_armv6.tar.gz"
    sha256 "f567c3c24e6c44215fc13d5dde8996d856019e4fa486277d08d48df860deaaf6"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/zaquestion/lab/releases/download/v0.20.0/lab_0.20.0_linux_arm64.tar.gz"
    sha256 "721f8eb2825e18b472e82e3a95a9ed077026786a81322c012a708d3401514b7b"
  end

  def install
    bin.install "lab"
  end

  test do
    system "git", "init"
    %w[haunted house].each { |f| touch testpath/f }
    system "git", "add", "haunted", "house"
    system "git", "commit", "-a", "-m", "Initial Commit"
    lab_env_config = "LAB_CORE_HOST=foo LAB_CORE_USER=bar LAB_CORE_TOKEN=baz"
    assert_match "haunted\nhouse", shell_output("#{lab_env_config} #{bin}/lab ls-files").strip
  end
end
