# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lab < Formula
  desc "Lab wraps Git or Hub, making it simple to clone, fork, and interact with repositories on GitLab"
  homepage "https://github.com/zaquestion/lab"
  version "0.24.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zaquestion/lab/releases/download/v0.24.0/lab_0.24.0_darwin_arm64.tar.gz"
      sha256 "3ce8baaff9ee99c17e1a2dc14bdc4b856ac1acbb856f2794278c42eac35d1ef6"

      def install
        bin.install "lab"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zaquestion/lab/releases/download/v0.24.0/lab_0.24.0_darwin_amd64.tar.gz"
      sha256 "c317b7588b9c58726bdba6c8185ceb0152f16fdb16fcceeded8b29a80112cbcc"

      def install
        bin.install "lab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/zaquestion/lab/releases/download/v0.24.0/lab_0.24.0_linux_armv6.tar.gz"
      sha256 "13df8a1a29bc6c7fa232a1c34c59890874815dc76b732483366d04016e08f5ae"

      def install
        bin.install "lab"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zaquestion/lab/releases/download/v0.24.0/lab_0.24.0_linux_amd64.tar.gz"
      sha256 "8d5baa6bc309df42d76147021e811e0a17f5134865f9d969796d074b5464adda"

      def install
        bin.install "lab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zaquestion/lab/releases/download/v0.24.0/lab_0.24.0_linux_arm64.tar.gz"
      sha256 "340c1b9bdbf39ee5e0e136a7ae2a23b4d209da44c8bcf780461f6250da9949dc"

      def install
        bin.install "lab"
      end
    end
  end

  test do
    system "git", "init"
    %w[haunted house].each { |f| touch testpath/f }
    system "git", "add", "haunted", "house"
    system "git", "commit", "-a", "-m", "Initial Commit"
    lab_env_config = "LAB_CORE_HOST=foo LAB_CORE_USER=bar LAB_CORE_TOKEN=baz"
    assert_match "haunted\nhouse", shell_output("#{lab_env_config} #{bin}/lab ls-files").strip
  end
end
